### ISSUE TITLE
Be able to set color for description parts of the text (assumptions)

### ISSUE THREAD

**Issue by alvipeo** [WPS/egon.io#129]
Since assumptions are part of the Description text, I'd suggest adding a feature to be able to change color of parts of the Description text. Or, as an option, to have Assumptions as a separate field.

**Comment by hofstef** [comment]
We've implemented colors for annotations with v2.1.0. For the description (in the header, on top of the canvas), we will not implement colors because 1.) it would require a different solution than coloring objects on the canvas and 2.)  I don't want the description text field to slowly turn into a rich text editor.
