### ISSUE TITLE
When there is a WorkObject before the first Actor, it does not appear in the replay

### ISSUE THREAD

**Issue by AlexanderZellober** [WPS/egon.io#133]
**Describe the bug**
When there is a WorkObject before the first Actor, it does not appear in the replay.

**To Reproduce**
Create a Story with a WorkObject that preceeds the first Actor.

**Expected behavior**
The WorkObject should be shown in the first Step of the Replay.

**Desktop:**
 - Modeler Version: 1.x

**Additional context**
This should not be prioritized high, since this does not reflect proper Domain-Story-Modeling Procedure

**Comment by hofstef** [comment]
You're right that modeling this way is not intended by the Domain Storytelling grammar. That's why I'd rather not encourage this modeling style by adding tool support to it. My advice to modelers who run into this issue is to ask where this first work object comes from - and make the answer the first sentence of the story.
