### ISSUE TITLE
modeling cannot model interactions between actors and/or workobject

### ISSUE THREAD

**Issue by d4e666** [WPS/egon.io#135]
**Describe the bug**
I'm trying to model the following and can't seem to create the connections I need

1. A coil of sheet metal arrives at a resource.
2. The coil is ispectected by an operator
3. an inspection report is entered in the system
4. the resource processes the coil
5. the coil is moved to the exit of that resource
6. the coil is inspected by a different operator
7. the operator enters another inspection report
8. the resource notifies a crane operator
9. the crane operator moves the coil from the resource to stock.

**To Reproduce**
[If applicable, attach a .dst file. ]
1. Add coil as a workobject/actor
10. Add resource as work object
11. Add Operator as an actor
12. I cannot create a link between then either the coil and the resource (if both are setup as work object) or coil and operator if the coil is setup as an actor.

Ik know I can set them up using 2 different icons, but does that not defeat the purpose? For me it would make sense that I can use the same icon for both. If I wanted to add the resource informs operator interaction, then I would have to draw 2 icons for the same item (next to each other) causing more confusion.

**Expected behavior**
I would expect that each icon play the role of both actor and workobject since the workobject itself can be an actor

**Screenshots**
![image](https://github.com/WPS/egon.io/assets/7936919/15017dce-8ac8-467d-902f-bd646d299f7a)

**Desktop (please complete the following information):**
 - Modeler Version: v2 beta
 - Browser: chrome
 - OS: Windows 10

**Additional context**
I'm trying to model the real world context so that I can use it to design the matching application.

**Comment by hofstef** [comment]
We deliberately designed the grammar of domain stories so that the elements of a model are either actors or work objects (and cannot change their type). Egon implements this grammar.

I think that with some changes to your model, you can express it as a domain story. The list of steps that you provided is a good starting point. I gave it a try (see attachment) but had to make some assumptions because I do not have any domain knowledge. For example, I assume that a coil cannot do anything on its own (it cannot arrive; it needs to be delivered) and is therefore modeled as a work object. 
![Wesley's Story egn](https://github.com/WPS/egon.io/assets/26813735/5da36be1-0119-4802-bf14-97791d8b4556)

**Comment by hofstef** [comment]
Closed as 'won't fix'

**Comment by d4e666** [comment]
what you wrote is exactly what happens in our flow. You may use this in your examples since this may help others getting around with complex flows that are difficult to model if you're new to the domain modeling mindset.

thx

**Comment by hofstef** [comment]
Great, happy that I could help!
