### ISSUE TITLE
Larger icons for touch operation

### ISSUE THREAD

**Issue by tburny** [WPS/egon.io#144]
**Is your feature request related to a problem? Please describe.**
I have a touchscreen in my Laptop and would like to use it for modeling, as it feels more haptic. While it works astonishingly well, the icons on one sidebar and in the "context menu" of the objects in the model are too small to grasp with your index finger.

**Describe the solution you'd like**
offer a "touch mode" that, as a first step, enlarges the icons. By having a "touch" mode, maybe some more opportunities for improving the modeling haptics (e.g. for touch tables) can be uncovered.

**Describe alternatives you've considered**
Zooming the browser window - this enlarges everything including the modeling surface, while only the UI itself should be enlarged.

**Additional context**
[Add any other context or screenshots about the feature request here.]

**Comment by hofstef** [comment]
Hi Tobias,
We don't actively support touch devices. The modeling toolkit that provides the foundation for Egon - bpmn.io - works with touch devices to some extent. However, they have dropped their support for touch devices recently (I guess because no touch support is better than a limited touch support). This means that Egon.io too will loose support for touch devices once we upgrade our dependencies. I've added a section on touch support to the [user guide](https://egon.io/howto#touch-support). We have no intention to build touch support on our own as I would rather invest time in other features like Miro integration :-)
