### ISSUE TITLE
Add Shortcut for Export of editable SVG

### ISSUE THREAD

**Issue by Morl99** [WPS/egon.io#159]
**Is your feature request related to a problem? Please describe.**
I find the export of editable SVGs a lot more useful than the JSON file. It is a great way to embed the model in other platforms (like confluence or miro) while still maintaining editability. It would be great, if this was easily accessible via a shortcut.

**Describe the solution you'd like**
Add a shortcut for the SVG export, maybe `ctrl + shift + s` would work well.

**Describe alternatives you've considered**
Always clicking manually, but the clickpath is quite tedious.

**Additional context**
I would be happy to open a PR with the changes if you are willing to accept it.

**Comment by hofstef** [comment]
Thanks, I think that this is a good idea since I believe that SVG is the preferred format of many users. 

- `ctrl + shift + s` is already used in Firefox for its built-in screenshot tool. 
- The SVG export has options to 1) add title and description 2) make background white instead of transparent. If the SVG export is triggered by a shortcut, we would have to decide which options to use. My guess is that both options should be selected since this is the default configuration.

Do you have any thoughts on that?

**Comment by Morl99** [comment]
Thank you for the comment. I think it is tough to find shortcuts that conflict with no browser on all platforms. The save shortcut today is also an override for the native save feature in chrome, although I really think that this is useless most of the time. I would argue the same thing here: since one can export high quality images, how often would people actually want to create screenshots? And if the do, could they use alternative means (OS screenshot tool, a menu entry)? Because of that, I would still vote for something with the key "s", as it is most intuitive.

If you think, that SVG should be the new default, we could also use "ctrl/cmd + s".

I strongly believe, that white background and include title/description should be the way to go.

**Comment by Morl99** [comment]
It looks like @DanielHeckert has implemented this in 5e020d535463c42a126e8665ca80256b3786162a choosing "ctrl + alt + s", which would work well for me on a MacOS as well. We could close this issue, although it would be nice to see a release of this in combination with my PR to #160.

**Comment by hofstef** [comment]
released with v2.3.0
