### ISSUE TITLE
Partial Import/Append from .dst

### ISSUE THREAD

**Issue by CoeusCC** [WPS/egon.io#69]
**Is your feature request related to a problem? Please describe.**
I'm used to the import, save, re-import workflow, but what I've found is that I'm building large "god-diagrams" and selectively deleting large chunks to get down to the information I want in a sub-domain or small process.

**Describe the solution you'd like**
In addition to an import that overwrites the entire workspace, it would be helpful to import another DST file, possibly to a temporary location or group and then to be able to place those objects into an open workspace. One idea might be to use the existing drag/drop for groups, and put the new objects in the "ghosted drag" status at import, and drop it on the next click to give it new location data.

**Describe alternatives you've considered**
I know the lasso tool works pretty well, so it might be possible to copy partial data to the clipboard and paste to a new area, maybe even on a different screen. With that approach the user could use different open tabs to manage separate files and simply copy/paste between contexts.

**Additional context**
I've begun using this quite heavily in the past few weeks, and would be a significant beneficiary of any improvements. I'm happy to do a little more research and attempt to make a PR if it would be helpful. If that's desired I'd appreciate the opportunity to discuss the feature with the repository owners to make sure that it fits the long-term goals of the project, and to get a better idea of any design or architectural concerns they might have.

**Comment by hofstef** [comment]
This issue has been open for years and I don't think that we will ever build it. It would require to solve (at least) the following problems:

- avoid clashes of IDs of appended model elements
- model elements only have a reference to their icon; the icon is defined in the icon set which means it would be necessary to also do a partial import the "source" icon set and then merge it into the "target" icon set
- change the sequence numbers of the copies activities so that they don't clash with the existing ones of the "target" domain story (most likely, the user would still need to renumber manually)

All this issues are solvable but with more effort that I am willing to invest. It would also challenge two core architectural assumptions: 1) domain stories are self-contained 2) 1 domain story = 1 model = 1 file
